INSTALL_TARGET_PROCESSES = SpringBoard

ARCHS = arm64

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = HideVPNIcon

HideVPNIcon_FILES = Tweak.x
HideVPNIcon_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
