include $(THEOS)/makefiles/common.mk

ARCHS = arm64 arm64e

TWEAK_NAME = TelegramUnrestrict


TelegramUnrestrict_FILES = Tweak.x
TelegramUnrestrict_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
